### ISSUE TITLE
PyPi guide is out of date

### ISSUE THREAD

**Issue by Nklobe** [runfalk/certbot-glesys#8]
Could you rewrite so that the PyPI-site just redirects to the github? 
I had some misshaps because i used the old PyPi guide

**Comment by runfalk** [comment]
A while back I renamed the package from `certbot-glesys` to `certbot-dns-glesys`. So there are two packages on PyPI. Since it's been so long now I've yanked all the versions from the old `certbot-glesys` package. I've also updated the link in the GitHub project to link to the correct package.

I tried to find a way of adding a note to the README on PyPI for `certbot-glesys` but couldn't find anything unfortunately. At least it shows in red that it has been yanked and installing using `pip install certbot-glesys` without a version specifier should not work anymore (meaning the instructions on the old package will no longer work):

```
$ pip install certbot-glesys
ERROR: Could not find a version that satisfies the requirement certbot-glesys (from versions: 0.1.0, 0.1.1, 0.2.0)
ERROR: No matching distribution found for certbot-glesys
```

I'm afraid that's the best I can do aside from nuking the package entirely.
